/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.anhle.forms;

import com.anhle.commons.FileManager;
import com.anhle.commons.Helper;
import com.anhle.models.Customer;
import com.anhle.models.Entity;
import com.anhle.models.Ordering;
import com.anhle.models.Product;
import com.anhle.panels.CustomerPanelManager;
import com.anhle.panels.OrderingPanelManager;
import com.anhle.panels.ProductionPanelManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anhle
 */
public class App extends javax.swing.JFrame {

    private Entity entities;
    
    private JPanel lastPanelAdded;
    /**
     * Creates new form App
     */
    public App() {
        
        initComponents();
        
        entities = new Entity();
        entities.customers = new ArrayList<Customer>();
        entities.orderings = new ArrayList<Ordering>();
        entities.products = new ArrayList<Product>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        btSaveData = new javax.swing.JMenuItem();
        btLoadData = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemProductions = new javax.swing.JMenuItem();
        itemCustomers = new javax.swing.JMenuItem();
        itemOrderings = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("File");

        btSaveData.setText("Save Data");
        btSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveDataActionPerformed(evt);
            }
        });
        jMenu2.add(btSaveData);

        btLoadData.setText("Load Data");
        btLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadDataActionPerformed(evt);
            }
        });
        jMenu2.add(btLoadData);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Manager");

        itemProductions.setText("Productions");
        itemProductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductionsActionPerformed(evt);
            }
        });
        jMenu6.add(itemProductions);

        itemCustomers.setText("Customer");
        itemCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCustomersActionPerformed(evt);
            }
        });
        jMenu6.add(itemCustomers);

        itemOrderings.setText("Orderings");
        itemOrderings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrderingsActionPerformed(evt);
            }
        });
        jMenu6.add(itemOrderings);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveDataActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            FileManager.SaveData(fileToSave.getAbsolutePath(), entities);
            JOptionPane.showMessageDialog(this,"Success");
        }
    }//GEN-LAST:event_btSaveDataActionPerformed

    private void btLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadDataActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            entities = FileManager.LoadData(selectedFile.getAbsolutePath());
            
            if(entities.customers == null)
                entities.customers = new ArrayList<Customer>();
            
            if(entities.orderings == null)
                entities.orderings = new ArrayList<Ordering>();
            
            if(entities.products == null)
                entities.products = new ArrayList<Product>();
            
            JOptionPane.showMessageDialog(this,"Success");
        }
    }//GEN-LAST:event_btLoadDataActionPerformed

    private void itemProductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductionsActionPerformed
        addNewPanel(new ProductionPanelManager(entities));
    }//GEN-LAST:event_itemProductionsActionPerformed

    private void itemCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCustomersActionPerformed
         addNewPanel(new CustomerPanelManager(entities));
    }//GEN-LAST:event_itemCustomersActionPerformed

    private void itemOrderingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrderingsActionPerformed
        
        if(entities.customers.size() == 0 || entities.products.size() == 0){
            JOptionPane.showMessageDialog(this,"product or customer is empty");
            return;
        }
        addNewPanel(new OrderingPanelManager(entities));
    }//GEN-LAST:event_itemOrderingsActionPerformed

    private void addNewPanel(JPanel panelManager){

        if(lastPanelAdded != null){
            remove(lastPanelAdded);
        }
        
        setLayout(new BorderLayout());
        add(panelManager);
        pack();
        
        lastPanelAdded = panelManager;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btLoadData;
    private javax.swing.JMenuItem btSaveData;
    private javax.swing.JMenuItem itemCustomers;
    private javax.swing.JMenuItem itemOrderings;
    private javax.swing.JMenuItem itemProductions;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    // End of variables declaration//GEN-END:variables
}
